[package]
name = "haskq-core"
version = "0.1.0"
edition = "2021"
description = "High-performance quantum computing simulation engine for HaskQ"
license = "MIT"
authors = ["HaskQ Team"]
repository = "https://github.com/ArsCodeAmatoria/HaskQ"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nalgebra = { version = "0.32", features = ["serde-serialize"] }
num-complex = { version = "0.4", features = ["serde"] }
rayon = { version = "1.7", optional = true }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
lazy_static = "1.4"
log = "0.4"
once_cell = "1.19"
libc = "0.2"

# Optional dependencies for different backends
blas-src = { version = "0.8", optional = true }
openblas-src = { version = "0.10", optional = true }
intel-mkl-src = { version = "0.8", optional = true }

# WASM support
wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }
web-sys = { version = "0.3", optional = true }

[features]
default = ["simd"]

# Core features
simd = []
parallel = ["rayon"]
blas = ["blas-src"]
mkl = ["intel-mkl-src", "blas"]
openblas = ["openblas-src", "blas"]

# Platform features  
wasm = ["wasm-bindgen", "js-sys", "web-sys"]
gpu = []
experimental = []

# Build profiles
full = ["parallel", "simd", "mkl"]
minimal = []

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3

[profile.bench]
inherits = "release"
debug = true

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
approx = "0.5"

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"] 