[package]
name = "haskq-sim"
version = "0.1.0"
edition = "2021"
description = "High-performance quantum circuit simulator compiled to WebAssembly"
license = "MIT"
repository = "https://github.com/HaskQ/haskq-sim"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
js-sys = "0.3"
nalgebra = "0.32"
num-complex = "0.4"
rayon = "1.7"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "Performance",
  "Window",
]

[features]
default = ["console_error_panic_hook"]

[dependencies.console_error_panic_hook]
version = "0.1.7"
optional = true

# Tell `rustc` to optimize for small code size.
[profile.release]
opt-level = "s"
lto = true 